sudo: required

language: go
go:
- 1.7
services:
  - docker

before_deploy:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region ap-southeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars

# trying to fix postgis bug which comes on the travis infrastructure that has sudo.
before_install:
 - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.5-postgis-2.2
 - sudo apt-get install -y xsltproc

install: true
addons:
  postgresql: '9.5'
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb.sh
script: 
- ./all.sh

deploy:
   - provider: script
     skip_cleanup: true
     script: ./build-push.sh fits-api
     on: 
       branch: master 
 
env:
    global:
         - secure: aAfJcT7S90E7eHVHnbW54iD6AhVZJW1qF9yEUmQ75t9pf12yAhr4wr8Jp7/Dy0JbQ4nk5kdv2KTEU5ZUYhnxexc936/iYEWauAYHvffFeXtKKEVovEuKI0nO0I3rU5kw8lMf2YCQQx1P2b4VV/foFh6SnT6QjBPmmZLXdI9l8Ck=
