sudo: required

language: go
go:
- 1.7.4
services:
  - docker

before_deploy:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region ap-southeast-2) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars

# trying to fix postgis bug which comes on the travis infrastructure that has sudo.
before_install:
 - export DEBIAN_FRONTEND=noninteractive;
   sudo -E apt-get -yq update &>> ~/apt-get-update.log;
   sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install postgresql-9.5-postgis-2.2
 - sudo apt-get install -y xsltproc

install: true
addons:
  postgresql: '9.5'
before_script:
- psql -U postgres -c "create extension postgis"
- ./database/scripts/initdb.sh
script: 
- ./all.sh

deploy:
   - provider: script
     skip_cleanup: true
     script: ./build-push.sh fits-api
     on: 
       branch: master

env:
    global:
         - secure: "RfKhktSoKtY/PZkzWu8ul4dayQ2IhFU2KL7TDdNptfAJlA1E0r+LQD3EStIph13eWI1MZsTYvXO3DXVGbp43VIQoVDBXmz3GxIU/6BT8p6Q3epX+fUn0Lod19PWwL2n/2mAYbE7LdVvzmEQr4YGs61TdpR8atQTP2WXCXn7beRw="
         - secure: "w9nrZfBdKV4pB7EqkowpF1Vp6YuphPKFrQ3ZYJPHWGWoDZQA3ID0Uk6zJaCxomtlVnj5TM1gjgRDwICYqkROPGquwwZ03Uj0IaMHeFljHPdo8H4VYjYWDpK5MlYo2P0fRFJGC9H3z9hc5qhqdS8yrHQgCzBT7paT/hhlINXY1UE="
